# geometricmodeling:		geometricmodeling.cpp
# 		g++  -o  geometricmodeling    geometricmodeling.cpp    -lm  -framework  OpenGL  -framework  GLUT 
# 		./geometricmodeling
geometricmodeling:		geometricmodeling.cpp
		g++ -o geometricmodeling  geometricmodeling.cpp libglut.so -lm -lGLEW -lGLU -lm -lGL -lm -lpthread -ldl -ldrm -lXdamage -lXfixes -lX11-xcb -lxcb-glx -lxcb-dri2 -lXxf86vm -lXext -lX11 -lpthread -lxcb -lXau -lXdmcp
		./geometricmodeling