# shadersproject:		shadersproject.cpp
# 		g++  -o  shadersproject    shadersproject.cpp    -lm  -framework  OpenGL  -framework  GLUT 
# 		./shadersproject
shadersproject:		shadersproject.cpp
		g++ -o shadersproject  shadersproject.cpp libglut.so -lm -lGLEW -lGLU -lm -lGL -lm -lpthread -ldl -ldrm -lXdamage -lXfixes -lX11-xcb -lxcb-glx -lxcb-dri2 -lXxf86vm -lXext -lX11 -lpthread -lxcb -lXau -lXdmcp
		./shadersproject