helicopter:		helicopter.cpp
##### LINUX ######
		g++  -o  helicopter    helicopter.cpp    -lm  -framework  OpenGL  -framework  GLUT
##### MAC ###### 
# 		g++ -o helicopter  helicopter.cpp  -lGL  -lGLU  libglut.so  -lm
