helicopter:		helicopter.cpp
		g++  -o  helicopter    helicopter.cpp    -lm  -framework  OpenGL  -framework  GLUT 
# helicopter:		helicopter.cpp
# 		g++ -o helicopter  helicopter.cpp  -lGL  -lGLU  libglut.so  -lm
