lightingproject:		lightingproject.cpp
		g++  -o  lightingproject    lightingproject.cpp    -lm  -framework  OpenGL  -framework  GLUT 
		./lightingproject
# lightingproject:		lightingproject.cpp
# 		g++ -o lightingproject  lightingproject.cpp  -lGL  -lGLU  libglut.so  -lm
# 		./lightingproject