lightingproject:		lightingproject.cpp
		g++  -o  lightingproject    lightingproject.cpp    -lm  -framework  OpenGL  -framework  GLUT 
		./lightingproject
# texturing:		texturing.cpp
# 		g++ -o texturing  texturing.cpp  -lGL  -lGLU  libglut.so  -lm
