project1:		rainbowRoad.cpp
##### MAC ######
		# g++ -o rainbowRoad  rainbowRoad.cpp  -lGL  -lGLU  libglut.so  -lm
##### LINUX ######
		g++  -o  rainbowRoad    rainbowRoad.cpp    -lm  -framework  OpenGL  -framework  GLUT 
