texturing:		texturing.cpp
		rm -rf texturing
		g++  -o  texturing    texturing.cpp    -lm  -framework  OpenGL  -framework  GLUT 
# texturing:		texturing.cpp
# 		g++ -o texturing  texturing.cpp  -lGL  -lGLU  libglut.so  -lm
